networks:
  demo:
    driver: bridge

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.35.0 # https://github.com/Azure/Azurite
    container_name: azurite
    restart: always
    command: "azurite-blob --blobHost 0.0.0.0 --blobPort 10000"
    ports:
      - 10000:10000 # Blob service
    # volumes:
    #   - ./azurite-blob:/data
    healthcheck:
      test: ["CMD", "node", "-e", "require('net').connect(10000,'127.0.0.1').on('connect',()=>process.exit(0)).on('error',()=>process.exit(1))"]
      interval: 15s
      timeout: 3s
      retries: 20
    networks:
      - demo

  init-blob-container:
    image: mcr.microsoft.com/azure-cli:latest
    container_name: init-blob-container
    restart: on-failure
    environment:
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      BLOB_CONTAINER_NAME: demo-blob-container
    command:
      - bash
      - -c
      - >-
        (echo "########################## CREATING BLOB... ##########################" &&
        echo "#### Attempting to create Blob container..." &&
        az storage container create --name $$BLOB_CONTAINER_NAME --connection-string $$AZURE_STORAGE_CONNECTION_STRING &&
        echo "########################## BLOB CREATED ##########################")
    networks:
      - demo
    depends_on:
      azurite:
        condition: service_healthy
